version: "3.7"
services:

  # cutten-database:
  #   container_name: cutten-db
  #   build:
  #     context: ./cutten-db
  #   volumes:
  #     - ./cutten-db/src:/cutten-db/src
  #   ports:
  #     - "7000:7000"

  cutten-server:
    container_name: cutten-server
    build:
      context: ./cutten-server
    volumes:
      - ./cutten-server/src:/cutten-server/src
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development

  cutten-web:
    container_name: cutten-web
    build:
      context: ./cutten-web
    volumes:
      - ./cutten-web/src:/cutten-web/src
    ports:
      - "9000:9000"
