version: "3.7"
services:

  cutten-server:
    container_name: cutten-server
    build:
      context: ./cutten-server
    volumes:
      - ./cutten-server/src:/cutten-server/src
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    depends_on: 
      - "cutten-db"

  cutten-web:
    container_name: cutten-web
    build:
      context: ./cutten-web
    volumes:
      - ./cutten-web/src:/cutten-web/src
    ports:
      - "9000:9000"

  cutten-db:
    container_name: 'cutten_db'
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'cutten_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./cutten_db/src:/var/lib/mysql
